--- #YAML:1.0
name:               wApua
version:            0.06.1
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::Parser:      2.99_06
    HTML::TokeParser:  ~
    LWP:               5.47
    LWP::UserAgent:    ~
    Tk:                800.000
    Tk::ROText:        ~
    URI:               1.03
    URI::Escape:       ~
    URI::file:         ~
    URI::Heuristic:    ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
