# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         wApua
version:      0.06
version_from: bin/wApua
installdirs:  site
requires:
    HTML::Parser:                  2.99_06
    HTML::TokeParser:              
    LWP:                           5.47
    LWP::UserAgent:                
    Tk:                            800.000
    Tk::ROText:                    
    URI:                           1.03
    URI::Escape:                   
    URI::file:                     
    URI::Heuristic:                

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
